### ISSUE TITLE
Check existing docs note styles

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-docs-theme-design#1]
Current Juju docs and tutorials has note styles with light backgrounds: https://jujucharms.com/docs/stable/getting-started

Should these be deprecated for the Vanilla notification style?

**Comment by yaili** [comment]
@spencerbygraves @kwm14 @anthonydillon thoughts?

**Comment by anthonydillon** [comment]
Absolutely, and will in fact when the Juju docs are ported to the docs
system. Currently there hosted and managed separately.

**Comment by yaili** [comment]
I see. I wasn't sure if this was supposed to be a variation of the notifications that we still wanted to keep.

**Comment by yaili** [comment]
@spencerbygraves can you comment on this?

**Comment by spencerbygraves** [comment]
Those are the old styles we are replacing. I'll close this.
