### ISSUE TITLE
Admonitions have no style

### ISSUE THREAD

**Issue by evilnick** [ubuntudesign/vanilla-docs-theme-design#3]
This was a minor annoyance in MAAS, but now we have many documentation projects moving to docs.ubuntu.com it becomes a much bigger problem. A documentation style which has no style for notes and other admonitions is incomplete, and documentation which uses no styles for this is far from the level we want to achieve.

This is what admonitions are **supposed to look like**:

## From Juju docs 
![image](https://cloud.githubusercontent.com/assets/115290/23958976/bdebe83a-099b-11e7-8200-a4c17e6d302e.png)

## From current conjure-up docs:
![image](https://cloud.githubusercontent.com/assets/115290/23959047/f0349846-099b-11e7-8073-01d9da1ebb97.png)

## From OpenStack documentation
![image](https://cloud.githubusercontent.com/assets/115290/23958998/cc7126e0-099b-11e7-9b1a-cc23e748c4a1.png)

## From Python.org docs:
![image](https://cloud.githubusercontent.com/assets/115290/23959029/de284468-099b-11e7-8bb9-b3a35f4839bd.png)

## From Google's cloud documentation:
![image](https://cloud.githubusercontent.com/assets/115290/23959132/38bf1302-099c-11e7-84fb-63bdf798bff8.png)

**Just as a reminder, here is our current eye-catching style for admonitions:**

![image](https://cloud.githubusercontent.com/assets/115290/23959395/0513e630-099d-11e7-972f-840cb1fadd5a.png)

Bonus points if you spotted both the note and the important warning there...

**Comment by matthewhelmke** [comment]
This is a significant issue if we are to have docs that are complete and which conform to accepted standards for documentation.

**Comment by evilnick** [comment]
N.B, this was originally discussed here: https://github.com/vanilla-framework/vanilla-framework/issues/868

**Comment by degville** [comment]
I too think this is important.

We (the docs team) were under the impression that various styles for admonitions were being implemented, but it has become difficult to track after the original discussion was closed. Does the [Colour accessibility update](https://github.com/canonical-websites/maas.io/issues/94) refer to the implementation of admonitions, for example?

**Comment by nottrobin** [comment]
I'm adding notifications styling to vanilla-docs-theme in https://github.com/vanilla-framework/vanilla-docs-theme/issues/29. This will fix https://github.com/vanilla-framework/vanilla-docs-theme/issues/28, but it doesn't yet mean that this can be used by the docs team in actual documentation.

To achieve that, documentation-builder needs updating to use the new version of vanilla-docs-theme, and generate the correct markup to make use of the new styles.

I'm working on adding that functionality to documentation-builder now, and will track it in https://github.com/CanonicalLtd/documentation-builder/issues/64.

**Comment by nottrobin** [comment]
I've now created https://github.com/CanonicalLtd/documentation-builder/pull/65 which gives you the ability to create [vanilla notifications](https://docs.vanillaframework.io/patterns/notification/) in documentation.

I am aware that this is not the same as the standard set of Admonitions defined in the DocBook standard, but it is all we have designs for at this stage, so I think we should merge this and start using the Vanilla notifications for now.

It's up to the docs team whether this solution is acceptable for the long term of if we need to continue this discussion to fully design a separate set of DocBook Admonition notifications for the vanilla-docs-theme.

**Comment by spencerbygraves** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs admonitions](https://trello.com/c/aEekdV1Y/816-docs-admonitions)

**Comment by spencerbygraves** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs admonitions](https://trello.com/c/aEekdV1Y/816-docs-admonitions)

**Comment by spencerbygraves** [comment]
Hi @evilnick To confirm, are these all the categories needed?

Info, tip, note, caution, and warning

I'll update the designs to include them.

**Comment by evilnick** [comment]
Hi, yes, those are the ones we currently have a need for, thanks!

**Comment by spencerbygraves** [comment]
Hi @evilnick Do you have some examples for each of those categories please? Perhaps you can point me to them in the docs.

Thanks

**Comment by spencerbygraves** [comment]
Hi @evilnick I've created these designs for admonitions, which follow our notification style.

![image](https://cloud.githubusercontent.com/assets/9105999/24497510/93a962e8-1533-11e7-9d7a-32f4a1d26dc3.png)

**Comment by matthewhelmke** [comment]
@evilnick is out until Monday. In the meanwhile, I'll say that I like how those look.

**Comment by yaili** [comment]
Should this issue be marked as closed, following the pattern name changes?

**Comment by yaili** [comment]
Asking again. Is this considered closed?

**Comment by pmatulis** [comment]
I thought the current admonishment styles were temporary, quickly implemented from the current style in the MAAS web UI. They certainly look very similar. Anyway, visually speaking, the code blocks and the admonishments are also very similar, resulting in a "blocky" user experience, as shown in the below screenshot:

![maas-admonishments](https://user-images.githubusercontent.com/6303808/27834647-bf30ac6a-60a5-11e7-9d85-b7babf4e9e64.png)

I much prefer a coloured background with no border, as exemplified in @evilnick 's OpenStack and Google cloud screenshots. Ultimately, though, we need to be able to stylishly marry the various elements (code blocks, admonishments) together, so maybe the code blocks also can be adjusted.

**Comment by evilnick** [comment]
Yes, I thought we were going to revisit this and add colours/icons

@spencerbygraves I liked your designs, though I think that some subtle background would help separate the text from the body copy also

**Comment by spencerbygraves** [comment]
@evilnick I don't remember any discussion to revisit the designs added here on March 30, those have the colours and icons based on the categories you gave us.

**Comment by evilnick** [comment]
Ok cool - thanks I wasn't aware all these had been added as MAAS is really the only place they are currently used, and due to not having them available before, we probably haven't used all the types. 

i suggest we close this issue then and open a new one if/when we have some more examples

**Comment by spencerbygraves** [comment]
@evilnick thanks, I'll close this then.
