### ISSUE TITLE
The API documentation no longer has anchors

### ISSUE THREAD

**Issue by evilnick** [ubuntudesign/vanilla-docs-theme-design#4]
Moved from: https://github.com/CanonicalLtd/maas-docs/issues/349 as reported by @blakerouse

>The API documentation no longer has anchors. Without anchors its impossible to point someone to an API endpoint when they ask a question. I can only give them the page and then they have to search for it. Anchor links allow us to give a link that auto scrolls to the correct location.

The anchor class is generated correctly from the docs, but isn't implemented in the style

**Comment by anthonydillon** [comment]
The ids are created for the TOC on the right-hand side. That said we should create an anchor pattern and have the documentation-builder add a link to the headings to utilise the anchor link.

**Comment by kwm14** [comment]
Moved issue to correct repo [vanilla-docs-theme](https://github.com/vanilla-framework/vanilla-docs-theme/issues/44). Closing issue.
