### ISSUE TITLE
Add link to parent site

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-docs-theme-design#5]

**Comment by spencerbygraves** [comment]
The header in the latest design has the logo, followed by a separating line and a title. We could have the logo take you to the parent site, and the title be the home link for the docs.

![image](https://cloud.githubusercontent.com/assets/9105999/24870491/5d1461b8-1e0e-11e7-841f-25ecedc35eb3.png)

**Comment by yaili** [comment]
I think it would be confusing for the logo to take you to another site.

**Comment by anthonydillon** [comment]
Could we not use words like <- Back to jujucharms.com | Logo | Documentation

**Comment by yaili** [comment]
Not sure about the word "back" because you might not have been there… but yes, something like that.

**Comment by spencerbygraves** [comment]
I'm not sure about adding a link to the header. I've tried it at the top of the left nav, separated by a line. There's a version with a back chevron, but as Lil says, you might not have come from there. There's also a version with the external link icon.

**Chevron**
![image](https://cloud.githubusercontent.com/assets/9105999/24950446/feb13c5c-1f68-11e7-8276-2ea25e5634ca.png)

**Icon**
![image](https://cloud.githubusercontent.com/assets/9105999/24950479/13190d00-1f69-11e7-8208-ac9091ecb42f.png)

**Comment by yaili** [comment]
They both _look_ good, but I don't know if they are confusing to someone who visits the docs… what if they were at the bottom, either above or below the Help/Report issue links?

**Comment by spencerbygraves** [comment]
Might be too hidden down there. Github have 'Return to Github' top right. Perhaps we have it next to the search?

![image](https://cloud.githubusercontent.com/assets/9105999/25178999/fbf2433e-24ff-11e7-9b93-3d1a3b12fb04.png)

**Comment by yaili** [comment]
Where is the GitHub example? Can you send a link?

**Comment by spencerbygraves** [comment]
https://help.github.com/

**Comment by spencerbygraves** [comment]
As agreed in the design review yesterday, I've moved the link to the bottom of the left nav, separated  by a line.

![image](https://cloud.githubusercontent.com/assets/9105999/25429324/7fbd6188-2a70-11e7-8c36-3136fa520a81.png)
